apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rook-ceph-metrics
  namespace: monitoring
  labels:
    app: rook-ceph-mgr
spec:
  endpoints:
  - port: http-metrics
    interval: 10s 
  selector:
    matchLabels:
      app: rook-ceph-mgr
  namespaceSelector:
    matchNames:
    - rook-ceph