kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-pvc
  namespace: default
  annotations:
    volume.beta.kubernetes.io/storage-class: "gluster"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi