apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: redis
spec:
  selector:
    app: redis
  type: NodePort
  ports:
  - name: client
    protocol: TCP
    port: 6379
    targetPort: 6379
    nodePort: 30379
  - name: gossip
    protocol: TCP
    port: 16379
    targetPort: 16379
    