kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: redis
  namespace: redis
  labels:
    app: redis
spec:
  replicas: 1
  serviceName: redis
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      volumes:
        - name: localtime
          hostPath:
            path: /etc/localtime
        - name: redis-config
          configMap:
            name: redis-config
      containers:
        - name: redis
          image: redis:6.2.5
          command:
            - redis-server
          args:
            - /etc/redis/redis.conf
          ports:
            - name: tcp-6379
              containerPort: 6379
              protocol: TCP
          volumeMounts:
            - name: localtime
              mountPath: /etc/localtime
              readOnly: true
            - name: redis-storage
              mountPath: /data
            - name: redis-config
              readOnly: true
              mountPath: /etc/redis/
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
  volumeClaimTemplates:
    - kind: PersistentVolumeClaim
      apiVersion: v1
      metadata:
        name: redis-storage
        namespace: redis
      spec:
        accessModes:
          - ReadWriteMany
        resources:
          requests:
            storage: 5Gi
        storageClassName: gluster

